# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'. 
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme:

url    : "ppsp-team.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog

title      : The PPSP laboratory
email      : contact@ppsp.team #this is also the email contact forms will go to
description: "The Precision Psychiatry and Social Physiology team combines computational biology and social neuroscience approaches to pave the way for a Predictive, Preventive, Personalized, Prescriptive, and Participatory (5P) medicine, especially for mental disorders."
author     : Guillaume Dumas
#logo:     #optional, defaults to site title
#  path: assets\img\fundings\creative-market.jpg
#  height: 60 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  papers:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mgepllgp" 